name: CI - Docker - apis/package-info

on:
  push:
    branches: [ main ]
    paths:
      - 'apis/package-info/**'
      - '.github/workflows/ci-package-info.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: zchryr/health
  IMAGE_NAME: package-info

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Log in to the Container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.16.0
        with:
          context: ./apis/package-info
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest