name: CI - Docker - dep-extractor

on:
  push:
    paths:
      - 'dep_extractor/action/**'
      - 'dep_extractor/requirements.txt'
      - 'dep_extractor/**.py'
      - '.github/workflows/publish-dep-extractor.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch Docker image
        working-directory: dep-extractor
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/health/dep-extractor
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_ID:latest . --push