name: CI - API Tests - apis/repo-health-check

on:
  push:
    paths:
      - 'apis/repo-health-check/**'
  pull_request:
    paths:
      - 'apis/repo-health-check/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/repo-health-check

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests with coverage
      run: |
        python -m pytest test_app.py --cov=app --cov-report=term-missing

    - name: Check coverage threshold
      run: |
        coverage=$(python -m pytest test_app.py --cov=app --cov-report=term-missing | grep "TOTAL" | awk '{print $4}' | sed 's/%//')
        if (( $(echo "$coverage < 50" | bc -l) )); then
          echo "Coverage is below 50% threshold"
          exit 1
        fi