name: CI - API Tests - apis/package-info

on:
  push:
    paths:
      - 'apis/package-info/**'
  pull_request:
    paths:
      - 'apis/package-info/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apis/package-info

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests with coverage
      id: coverage
      run: |
        coverage run -m pytest test_app.py
        coverage report --show-missing

    - name: Check coverage threshold
      run: |
        COVERAGE=$(coverage report | grep TOTAL | awk '{print $4}' | sed 's/%//')
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "Coverage is below 80% threshold (current: $COVERAGE%)"
          exit 1
        else
          echo "Coverage is above threshold (current: $COVERAGE%)"
        fi